before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
dist: go-dist
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/cassowary
  binary: cassowary
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm64
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
    386: i386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'LICENSE'
    - 'README.md'
    - 'cass-logo.png'
